name: Simple Local

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
        working-directory: .github  # Define o diretório de trabalho para a pasta .github
      - name: Install moment
        run: npm install moment
        working-directory: .github  # Define o diretório de trabalho para a pasta .github
      - name: Run app.js
        run: node app.js
        working-directory: .github  # Define o diretório de trabalho para a pasta .github
